export enum ApexFeatures {
  gep_internal = 'gep_internal',
  death = 'death',
  kill = 'kill',
  match_state = 'match_state',
  me = 'me',
  revive = 'revive',
  team = 'team',
  roster = 'roster',
  kill_feed = 'kill_feed',
  rank = 'rank',
  match_summary = 'match_summary',
  location = 'location',
  match_info = 'match_info',
  phase = 'phase',
  victory = 'victory',
  damage = 'damage',
  inventory = 'inventory',

}
